import type {
  DetectionCorrectionRecord,
  DetectionRecord,
  FrameDetailRecord,
  FramePointCloudResponse,
  InferenceRunRecord,
} from "../types";

export const sampleFrame: FrameDetailRecord = {
  frame_id: "frame-001",
  dataset_id: 1,
  image_path: "frames/frame-001.png",
  latitude: 48.14542,
  longitude: 11.56661,
  heading_degrees: 92.5,
  timestamp: "2026-03-20T10:15:00Z",
  image_width: 1920,
  image_height: 1080,
  pitch_degrees: null,
  roll_degrees: null,
  camera_intrinsics_json: null,
  sequence_id: "sequence-1",
  depth_path: null,
  preview_url: "/datasets/1/frames/frame-001/preview",
};

export const sampleRun: InferenceRunRecord = {
  id: 7,
  dataset_id: 1,
  run_type: "detection",
  status: "completed",
  model_name: "yolo11n",
  model_path: "data/raw/models/yolo11n.pt",
  frame_count: 2,
  processed_frame_count: 2,
  detection_count: 3,
  error_message: null,
  started_at: "2026-03-20T10:16:00Z",
  completed_at: "2026-03-20T10:17:00Z",
};

export const sampleDetections: DetectionRecord[] = [
  {
    id: 11,
    inference_run_id: 7,
    frame_id: "frame-001",
    class_name: "car",
    confidence_score: 0.92,
    x_min: 96,
    y_min: 54,
    x_max: 960,
    y_max: 540,
    created_at: "2026-03-20T10:17:00Z",
  },
];

export const sampleSavedCorrection: DetectionCorrectionRecord = {
  id: 31,
  detection_id: 11,
  review_status: "pending",
  created_at: "2026-03-20T10:18:00Z",
  updated_at: "2026-03-20T10:18:00Z",
  original_detection: {
    detection_id: 11,
    inference_run_id: 7,
    frame_id: "frame-001",
    class_name: "car",
    confidence_score: 0.92,
    x_min: 96,
    y_min: 54,
    x_max: 960,
    y_max: 540,
    source: "original",
  },
  corrected_detection: {
    detection_id: 11,
    inference_run_id: 7,
    frame_id: "frame-001",
    class_name: "traffic_sign",
    confidence_score: 0.92,
    x_min: 0,
    y_min: 40,
    x_max: 1920,
    y_max: 560,
    source: "corrected",
  },
  effective_detection: {
    detection_id: 11,
    inference_run_id: 7,
    frame_id: "frame-001",
    class_name: "traffic_sign",
    confidence_score: 0.92,
    x_min: 0,
    y_min: 40,
    x_max: 1920,
    y_max: 560,
    source: "corrected",
  },
};

export const samplePointCloudResponse: FramePointCloudResponse = {
  frame_id: "frame-001",
  state: "completed",
  detail: null,
  run: {
    id: 12,
    dataset_id: 1,
    frame_id: "frame-001",
    run_type: "point_cloud",
    status: "completed",
    model_name: "stored-depth-conversion",
    model_path: "depth/run-1.npy",
    frame_count: 1,
    processed_frame_count: 1,
    detection_count: 0,
    error_message: null,
    started_at: "2026-03-20T10:21:00Z",
    completed_at: "2026-03-20T10:21:05Z",
  },
  artifact: {
    id: 22,
    inference_run_id: 12,
    frame_id: "frame-001",
    source_depth_artifact_id: 9,
    point_cloud_uri: "dataset-1/frame-001/run-12.npz",
    point_format: "float32_npz_xyz",
    coordinate_system: "camera_local_right_handed_x_right_y_up_z_forward",
    source_point_count: 6,
    point_count: 3,
    subsample_step: 2,
    intrinsics_source: "frame_metadata",
    fx: 812.1,
    fy: 811.0,
    cx: 999.3,
    cy: 650.7,
    created_at: "2026-03-20T10:21:05Z",
  },
  payload: {
    points: [
      { x: -0.375, y: 0.125, z: 1 },
      { x: -0.125, y: -0.125, z: 1.5 },
      { x: 0.25, y: -0.2, z: 2.2 },
    ],
  },
};
